type Query {
  hello(name: String!): String!
  me: User
}

type User {
  sayHello(to: String!): String!
}

type Mutation {
  sendMessage(message: String!): String!
}

type Subscription {
  onMessage: String
}
