env:
  node: true
  es2020: true
plugins:
  - unicorn
extends:
  - "@hydre/eslint-config-hydre"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
# Nodejs support some experimental ecma features but not eslint
parser: "@babel/eslint-parser"
parserOptions:
  sourceType: module
  configFile: package.json
  ecmaVersion: 11